<a href="https://colab.research.google.com/github/sajalgoyal007/AIML-Training-Projects/blob/main/Practice/NumPy_you.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Basic array creation**

In [ ]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
a = [1, 2, 3, 4]
a

[1, 2, 3, 4]

In [ ]:
a = [1, 2, 3, 4, "Sajal"]
a

[1, 2, 3, 4, 'Sajal']

In [ ]:
np.array(a)

array(['1', '2', '3', '4', 'Sajal'], dtype='<U21')

In [ ]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((6, 6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((6, 6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1, 5, 3)
arr

array([1., 3., 5.])

In [ ]:
arr = np.linspace(1, 10, 3)
arr

array([ 1. ,  5.5, 10. ])

**Random Generation Function**

In [ ]:
import random as rand

In [ ]:
np.random.rand(5)

array([0.54286213, 0.10576175, 0.83170827, 0.60885752, 0.20394991])

In [ ]:
np.random.randn(5)  # In this number between -3 to +3

array([-2.8352012 , -1.29457901,  0.17935728,  0.5356117 , -0.24968259])

In [ ]:
np.random.randint(6)  #generate a number between the 0 to 6

2

In [ ]:
np.random.randint(6, 30, 10)

array([29, 21, 12, 14, 28,  7, 25, 18, 24, 12])

**Array Attributes**

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

**Array Methods**

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [ ]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

**Reshaping and Resizing**

In [ ]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(6, 5)

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

**NumPy indexing and Slicing of vectors**

In [ ]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[6]

np.int64(17)

In [ ]:
arr[9]

np.int64(20)

In [ ]:
arr[1:5]

array([12, 13, 14, 15])

**NumPy Indexing and Slicing of Matrix**

In [ ]:
arr = np.arange(1, 31).reshape(6, 5)

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[5]

array([26, 27, 28, 29, 30])

In [ ]:
arr[0, 0]

np.int64(1)

In [ ]:
arr[0, 4]

np.int64(5)

In [ ]:
arr[5, 4]

np.int64(30)

In [ ]:
slice = arr[0:2, 1:3]
slice

array([[2, 3],
       [7, 8]])

In [ ]:
slice2 = arr[3:, 3:]
slice2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:, 2]

array([ 3,  8, 13, 18, 23, 28])

**Boolean Indexing**

In [ ]:
arr = np.arange(11, 21)

In [ ]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = np.arange(11, 21)
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

**Array Operations**

Arithmetic Operations

In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])


In [ ]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a2-a1

array([5, 5, 5, 5, 5])

In [ ]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1//a2

array([0, 0, 0, 0, 0])

In [ ]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

**BroadCasting**

In [ ]:
l = [10, 20 , 30, 40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [ ]:
# l+10
for i in l:
  print(i+10)

20
30
40
50


In [ ]:
arr+10

array([20, 30, 40, 50])

**Deep And Shallow Copy**

In [ ]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a[4:6] * 10

array([50, 60])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a
b = a
#b = a.copy()

In [ ]:
b[0] = 99

In [ ]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Matrix operations**

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
a*b  #It is not the real matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [ ]:
a @ b

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [ ]:
a.T

array([[1, 3],
       [2, 4]])

**Advance Array Manipulation**


Stacking Array

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.column_stack((a, b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [ ]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(c, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

**Valid Sudoku**

In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
b = np.sum(s, axis = 1)

for i in b:
  if i != 45:
    print("Invalid Sudoku")
    break
else:
  print("For rows it is a Valid Sudoku")

For rows it is a Valid Sudoku


In [ ]:
c = np.sum(s, axis = 0)
for i in b:
  if i != 45:
    print("Invalid Sudoku")
    break
else:
  print("For columns it is a Valid Sudoku")

For columns it is a Valid Sudoku


In [ ]:
s[:3, :3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [ ]:
s[:3, 3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [ ]:
s[:3, 6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [ ]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [ ]:
for i in range(0, 9, 3):
  for j in range(0, 9, 3):
    n = s[i:i+3, j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45


**General Question**

In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [ ]:
#Find the average age of students.
np.mean(data[:, 0])

np.float64(18.4)

In [ ]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [ ]:
#Find the highest Science mark.
np.max(data[:, 2])

np.int64(95)

In [ ]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [ ]:
#Increase Math marks of all students by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [ ]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [ ]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis = 0)

array([86.6, 83.2])

In [ ]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [ ]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])